spring.application.name=bff-vitacare

server.port=8086

firebase.project-id=${FIREBASE_PROJECT_ID:vitacare-a6641}
user-service.base-url=${USER_SERVICE_URL:http://localhost:8085}
patient-service.base-url=${PATIENT_SERVICE_URL:http://localhost:8082}
measurement-service.base-url=${MEASUREMENT_SERVICE_URL:http://localhost:8083}
medication-service.base-url=${MEDICATION_SERVICE_URL:http://localhost:8084}
chatbot-service.base-url=${CHATBOT_SERVICE_URL:http://localhost:8080}